FROM ubuntu:xenial
MAINTAINER Leonardo Loures <luvres@hotmail.com>

## References:
# https://www.youtube.com/watch?v=iU5CzyyBfhY

ENV USER="3PThBqHfb1UVcZaZXtPAY4SC4fZNBNqCs7.1uvr3z" \
	CORES=4 \
	POOL="equihash.usa.nicehash.com" \
	PORT=3357

RUN \
	cd \
	&& apt-get update \
	&& apt-get install -y git cmake build-essential libboost-all-dev \
  \
	&& git clone -b Linux https://github.com/nicehash/nheqminer.git \
	&& cd nheqminer/cpu_xenoncat/Linux/asm \
	&& sh assemble.sh \
	&& cd ../../../Linux_cmake/nheqminer_cpu \
	&& cmake . \
	&& make -j $(nproc) \
  \
	&& mv nheqminer_cpu /usr/bin \
	&& cd \
	&& rm nheqminer -fR \
  \
	&& apt-get remove -y git cmake build-essential libboost-all-dev \
	&& apt-get autoremove -y \
	&& apt-get install -y libboost-system1.58.0 libboost-log1.58.0

CMD nheqminer_cpu -l $POOL:$PORT -u $USER -t $CORES
